/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kylelaker.aoc2023;

import org.junit.jupiter.api.Test;

class MainTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
