/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kylelaker.aoc2023.solutions;

import com.kylelaker.aoc2023.ProblemInput;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.FileInputStream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day1Test {
    @Test
    void day1SolvesPart1() throws Exception {
        // GIVEN
        Day1 solver = new Day1();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/1a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(142, solver.part1(input));
    }

    @Test
    void day1SovesPart2SampleInput() throws Exception {
        // GIVEN
        Day1 solver = new Day1();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/1b.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(281, solver.part2(input));

    }
}
