/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kylelaker.aoc2023.solutions;

import java.io.File;
import java.io.FileInputStream;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


import com.kylelaker.aoc2023.ProblemInput;

class Day1Test {
    @Test void day1SolvesPart1() throws Exception {
        // GIVEN
        Day1 solver = new Day1();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/1a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(solver.part1(input), "142");
    }

    @Test void day1SovesPart2SampleInput() throws Exception {
        // GIVEN
        Day1 solver = new Day1();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/1b.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(solver.part2(input), "281");

    }
}
