/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kylelaker.aoc2023.solutions;

import com.kylelaker.aoc2023.ProblemInput;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.FileInputStream;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day3Test {
    @Test
    void day3SolvesPart1() throws Exception {
        // GIVEN
        Day3 solver = new Day3();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/3a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(solver.part1(input), 4361);
    }

    @Test
    void day3SovesPart2SampleInput() throws Exception {
        // GIVEN
        Day3 solver = new Day3();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/3a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(solver.part2(input), 467835);
    }
}
