/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kylelaker.aoc2023.solutions;

import com.kylelaker.aoc2023.ProblemInput;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.FileInputStream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day5Test {
    @Test
    void day5SolvesPart1() throws Exception {
        // GIVEN
        Day5 solver = new Day5();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/5a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(35, solver.part1(input));
    }

    @Test
    void day5SovesPart2SampleInput() throws Exception {
        // GIVEN
        Day5 solver = new Day5();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/5a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(46, solver.part2(input));
    }
}
