/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kylelaker.aoc2023.solutions;

import com.kylelaker.aoc2023.ProblemInput;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.FileInputStream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day6Test {
    @Test
    void day6SolvesPart1() throws Exception {
        // GIVEN
        Day6 solver = new Day6();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/6a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(288, solver.part1(input));
    }

    @Test
    void day6SolvesPart1WithMath() throws Exception {
        // GIVEN
        Day6 solver = new Day6();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/6a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(288, solver.part1WithMath(input));
    }

    @Test
    void day6SovesPart2SampleInput() throws Exception {
        // GIVEN
        Day6 solver = new Day6();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/6a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(71503, solver.part2(input));
    }

    @Test
    void day6SolvesPart2WithMath() throws Exception {
        // GIVEN
        Day6 solver = new Day6();
        // WHEN
        File inputFile = new File(getClass().getClassLoader().getResource("inputs/6a.txt").getFile());
        ProblemInput input = ProblemInput.fromInputStream(new FileInputStream(inputFile));
        // THEN
        assertEquals(71503, solver.part2WithMath(input));
    }
}
